FROM python:3.11-slim

WORKDIR /app

COPY backend/requirements.txt ./backend/requirements.txt
RUN pip install --no-cache-dir -r ./backend/requirements.txt

COPY backend ./backend
COPY src/data ./src/data

WORKDIR /app/backend
EXPOSE 8000

CMD ["python", "main.py"]
